2024-11-05 13:21:23,591 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [8216] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-05 13:21:23,606 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [8216] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-05 13:21:24,057 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [8216] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-05 13:21:24,228 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [8216] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-05 13:21:24,387 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [8216] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-05 13:21:24,426 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [8216] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-05 13:21:29,563 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [8216] [MainThread] - DEBUG - Model name detected: old_money
2024-11-05 13:21:29,563 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [8216] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-05 13:21:29,563 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [8216] [MainThread] - DEBUG - Get key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 returned value: None
2024-11-05 13:21:29,563 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [8216] [MainThread] - DEBUG - ModelPath instance 2 initialized for old_money.
2024-11-05 13:21:29,563 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [8216] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-05 13:21:29,564 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [8216] [MainThread] - DEBUG - Get key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 returned value: None
2024-11-05 13:21:29,564 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:340] [8216] [MainThread] - INFO - Writing <built-in method title of str object at 0x1051deab0>Path object to cache for model old_money.
2024-11-05 13:21:29,564 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:170] [8216] [MainThread] - DEBUG - Cache saved to file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-05 13:21:29,564 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:133] [8216] [MainThread] - DEBUG - Set key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 with value: <model_path.ModelPath object at 0x17f0f0e90>
2024-11-05 13:21:29,564 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:243] [8216] [MainThread] - INFO - Fetching data...
2024-11-05 13:21:29,564 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:37] [8216] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-05 13:21:29,564 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [8216] [MainThread] - DEBUG - Model name detected: old_money
2024-11-05 13:21:29,565 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [8216] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-05 13:21:29,565 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [8216] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x17f460c50>
2024-11-05 13:21:29,565 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [8216] [MainThread] - INFO - ModelPath instance old_money found in GlobalCache. Using cached instance.
2024-11-05 13:21:29,565 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [8216] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-05 13:21:29,565 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [8216] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-05 13:21:29,565 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [8216] [MainThread] - DEBUG - ModelPath instance 3 initialized for old_money.
2024-11-05 13:21:29,565 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [8216] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-05 13:21:29,565 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [8216] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x17f3fca10>
2024-11-05 13:21:29,566 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:484] [8216] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_old_money.py imported successfully.
2024-11-05 13:21:29,571 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:45] [8216] [MainThread] - INFO - Found queryset for old_money in common_querysets
2024-11-05 13:21:29,571 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [8216] [MainThread] - INFO - Publishing queryset fatalities002_pgm_escwa_drought
2024-11-05 13:21:29,572 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [8216] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-05 13:21:30,175 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [8216] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-05 13:21:30,176 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [8216] [MainThread] - INFO - Fetching queryset fatalities002_pgm_escwa_drought
2024-11-05 13:21:30,180 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [8216] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-05 13:21:52,311 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [8216] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities002_pgm_escwa_drought?start_date=121&end_date=444 HTTP/11" 200 185580588
2024-11-05 13:22:15,643 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:377] [8216] [MainThread] - WARNING - DataFrame contains non-np.float64 numeric columns. Converting the following columns: greq_1_excluded
2024-11-05 13:22:15,649 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [8216] [MainThread] - WARNING - {'old_money data alert 1': ' alarm: feature zero; offender: tlag1_dr_sev_gs, threshold: 0.95 Severity: 2 Timestamp: 2024-11-05 13:22:15\n, '}
2024-11-05 13:22:15,650 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [8216] [MainThread] - WARNING - {'old_money data alert 2': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-05 13:22:15\n, '}
2024-11-05 13:22:15,650 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [8216] [MainThread] - WARNING - {'old_money data alert 3': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-05 13:22:15\n'}
2024-11-05 13:22:15,650 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [8216] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/raw/calibration_data_fetch_log.txt
2024-11-05 13:22:15,650 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:250] [8216] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/raw/calibration_viewser_df.pkl
2024-11-05 13:22:15,788 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/dataloaders/get_data.py [get_data.py:12] [8216] [MainThread] - DEBUG - DataFrame shape: (4247640, 29)
2024-11-05 13:22:23,002 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [8216] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-05 13:22:23,079 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [8216] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-05 13:22:23,102 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [8216] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-05 13:22:29,661 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/management/execute_model_tasks.py [execute_model_tasks.py:57] [8216] [MainThread] - INFO - Training model old_money...
2024-11-05 13:22:29,662 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [8216] [MainThread] - DEBUG - Model name detected: old_money
2024-11-05 13:22:29,662 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [8216] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-05 13:22:29,662 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [8216] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x17ef564d0>
2024-11-05 13:22:29,662 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [8216] [MainThread] - INFO - ModelPath instance old_money found in GlobalCache. Using cached instance.
2024-11-05 13:22:29,662 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [8216] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-05 13:22:29,662 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [8216] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-05 13:22:29,662 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [8216] [MainThread] - DEBUG - ModelPath instance 4 initialized for old_money.
2024-11-05 13:22:29,663 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [8216] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-05 13:22:29,663 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [8216] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x17efea9d0>
2024-11-05 13:22:30,992 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/darts/timeseries.py [timeseries.py:821] [8216] [MainThread] - WARNING - UserWarning: `time_col` was not set and `df` has a monotonically increasing (time) index. This results in time series groups with non-overlapping (time) index. You can ignore this warning if the index represents the actual index of each individual time series group.
2024-11-05 13:26:58,367 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:119] [8216] [MainThread] - INFO - Log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/generated/calibration_log.txt
2024-11-05 13:26:58,676 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/management/execute_model_tasks.py [execute_model_tasks.py:71] [8216] [MainThread] - INFO - Done. Runtime: 4.593 minutes.

2024-11-05 13:27:05,301 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [8216] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-05 13:27:07,361 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [8216] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
